name: Upload Python Package

on:
  release:
    types: [ published ]
env:
  PYTHONPATH: ${{ github.workspace }}

permissions:
  contents: read

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Test with pytest
        run: pytest
        env:
          PYTHONPATH: ${{ env.PYTHONPATH }}
      - name: Build package
        run: python -m build
      - name: Publish package
        uses: pypa/gh-action-pypi-publish@latest
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
